# -*- coding: utf-8 -*-
"""wine_quality_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwDR8HmjZHqsDpfKZPjGr2B2rj5HU3Ue
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("wine_quality_prediction.pkl")

st.title("Wine Quality Merged System")

st.write("you can enter the data from sensor and check whether your machine will work or fail under certain condition")

fixed acidity= st.number_input("fixed acidity")
volatile acidity = st.number_input("volatile acidity")
citric acid = st.number_input("citric acid")
residual sugar = st.number_input("residual sugar")
chlorides = st.number_input("chlorides")
free sulfur dioxide = st.number_input("free sulfur dioxide")
total sulfur dioxide = st.number_input("total sulfur dioxide")
density = st.number_input("density")
pH = st.number_input("pH")
sulphates = st.number_input("sulphates")
alcohol = st.number_input("alcohol")
quality = st.number_input("quality")
type = st.number_input("type")


df = pd.DataFrame({
    "fixed acidity": [fixed acidity],
    "volatile acidity": [volatile acidity],
    "citric acid": [citric acid],
    "residual sugar": [residual sugar],
    "chlorides": [chlorides],
    "free sulfur dioxide": [free sulfur dioxide],
    "total sulfur dioxide": [total sulfur dioxide],
    "density": [density],
    "pH": [pH],
    "sulphates": [sulphates],
    "alcohol": [alcohol],
    "quality": [quality],
    "type": [type],
})

if st.button("Predict"):
    prediction = model.predict(df)
    if prediction[0] ==1:
      st.error("Wine quality bad")
    else:
      st.success("Wine quality Good")