# -*- coding: utf-8 -*-
"""wine_quality_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwDR8HmjZHqsDpfKZPjGr2B2rj5HU3Ue
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("wine_quality_model.pkl")

st.title("Wine Quality Merged System")

st.write("you can enter the data from sensor and check whether your machine will work or fail under certain condition")

fixed_acidity= st.number_input("Fixed Acidity")
volatile_acidity = st.number_input("Volatile Acidity")
citric_acid = st.number_input("Citric Acid")
residual_sugar = st.number_input("Residual Sugar")
chlorides = st.number_input("Chlorides")
free_sulfur_dioxide = st.number_input("Free Sulfur Dioxide")
total_sulfur_dioxide = st.number_input("Total Sulfur Dioxide")
density = st.number_input("Density")
pH = st.number_input("pH")
sulphates = st.number_input("Sulphates")
alcohol = st.number_input("Alcohol")
quality = st.number_input("Quality")
type = st.number_input("type")

df = pd.DataFrame({
    'fixed acidity': [fixed_acidity],
    'volatile acidity': [volatile_acidity],
    'citric acid': [citric_acid],
    'residual sugar': [residual_sugar],
    'chlorides': [chlorides],
    'free sulfur dioxide': [free_sulfur_dioxide],
    'total sulfur dioxide': [total_sulfur_dioxide],
    'density': [density],
    'pH': [pH],
    'sulphates': [sulphates],
    'alcohol': [alcohol],
    "quality": [quality],
    "type": [type]
})

if st.button("Predict Quality"):
    prediction = model.predict(df)
    st.success(f"Predicted Wine Quality: {prediction[0]}")
